// ============================================================================
// GENERATED by `npm run build:nodes` — DO NOT EDIT.
// Wrapper: workflows/code-nodes/completeResolve.wrapper.js
// Core inlined verbatim from: scripts/notify.js
// Paste this whole file into the n8n Code node.
// ============================================================================

// n8n Code node — "Resolve" (F4)  (THIN WRAPPER — do not put logic here)
// Core (notify.js) inlined by `npm run build:nodes`. Paste completeResolve.built.js.
//
// Input: the fetched Onboarding_Tasks record. Ref: "Parse Callback".
// Output: outcome (unauthorized | already-final | apply) + everything the downstream
// branches need (status, ids, message id/chat for the edit, answer text).

// ---- inlined from scripts/notify.js ----
// notify.js — pure logic for F3 (grouped notifications) and F4 (completion).
//
// No network, no Telegram, no Date.now(). The only time-dependent input, "today", is
// injected as an ISO date. `officeToday` derives that date in a timezone from a given
// moment — kept here so the day-boundary rule is testable, not buried in n8n.

/**
 * The office-local calendar date (ISO YYYY-MM-DD) for a given moment.
 * en-CA formats as YYYY-MM-DD; the timeZone makes it office-local, not UTC — this is
 * what makes "Due_Date <= today" correct regardless of what UTC clock the job runs on.
 * @param {Date} now
 * @param {string} timeZone - e.g. "Europe/Istanbul"
 */
function officeToday(now, timeZone) {
  return now.toLocaleDateString('en-CA', { timeZone });
}

/**
 * Tasks due for a notification today: Pending, due on/before today, not yet notified.
 * Dates are compared as ISO strings (YYYY-MM-DD sorts chronologically), so this is a
 * date comparison, never a moment comparison.
 */
function selectDueTasks(tasks, today) {
  return tasks.filter(
    (t) => t.status === 'Pending' && !t.notified_at && String(t.due_date) <= today,
  );
}

/**
 * Group tasks by assignee Telegram id, preserving first-seen order — one message per
 * person, not one per task.
 * @returns {{ assignee_telegram_id: string, tasks: object[] }[]}
 */
function groupByAssignee(tasks) {
  const groups = new Map();
  for (const t of tasks) {
    const key = String(t.assignee_telegram_id);
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(t);
  }
  return [...groups.entries()].map(([assignee_telegram_id, ts]) => ({
    assignee_telegram_id,
    tasks: ts,
  }));
}

/**
 * Render a grouped message as Telegram payload pieces: `text` plus an inline keyboard.
 * Works for the first send (all Pending) and for re-render after a tap (mixed statuses):
 * final tasks show a marker and lose their buttons; Pending tasks keep Done / Not applicable.
 * Blocking tasks are flagged. Callback data is `done:<id>` / `skip:<id>`.
 * @returns {{ text: string, inline_keyboard: object[][] }}
 */
function renderMessage(tasks) {
  const byEmployee = new Map();
  for (const t of tasks) {
    if (!byEmployee.has(t.employee_id)) byEmployee.set(t.employee_id, []);
    byEmployee.get(t.employee_id).push(t);
  }

  const lines = ['Onboarding tasks:'];
  const inline_keyboard = [];

  for (const [, empTasks] of byEmployee) {
    const { employee_name, start_date } = empTasks[0];
    lines.push('', `${employee_name} — starts ${start_date}`);
    for (const t of empTasks) {
      if (t.status === 'Done') {
        lines.push(`  [done] ${t.title}`);
      } else if (t.status === 'Skipped') {
        lines.push(`  [n/a] ${t.title}`);
      } else {
        const flag = t.blocking ? '⚠️ ' : '';
        lines.push(`  ${flag}${t.title} (due ${t.due_date})`);
        inline_keyboard.push([
          { text: '✅ Done', callback_data: `done:${t.id}` },
          { text: '🚫 Not applicable', callback_data: `skip:${t.id}` },
        ]);
      }
    }
  }

  return { text: lines.join('\n'), inline_keyboard };
}

const CALLBACK_RE = /^(done|skip):(rec[A-Za-z0-9]+)$/;

/**
 * Parse Telegram callback_data. Strict: anything that is not exactly `done:<recId>` or
 * `skip:<recId>` returns null (caller logs and ignores) — callbacks can arrive from a
 * stale message or another bot, so this must never throw.
 * @returns {{ action: 'done'|'skip', taskId: string } | null}
 */
function parseCallback(data) {
  if (typeof data !== 'string') return null;
  const m = CALLBACK_RE.exec(data);
  return m ? { action: m[1], taskId: m[2] } : null;
}

/**
 * Decide what a callback should do, given the current task, who tapped, and the action.
 * - not the assignee            -> 'unauthorized'
 * - task already Done/Skipped   -> 'already-final' (idempotent: do not rewrite Completed_At)
 * - otherwise                   -> 'apply' with the target status
 * @returns {{ outcome: 'unauthorized'|'already-final'|'apply', status?: 'Done'|'Skipped' }}
 */
function resolveCallback({ task, fromTelegramId, action }) {
  if (String(task.assignee_telegram_id) !== String(fromTelegramId)) {
    return { outcome: 'unauthorized' };
  }
  if (task.status !== 'Pending') {
    return { outcome: 'already-final' };
  }
  return { outcome: 'apply', status: action === 'done' ? 'Done' : 'Skipped' };
}

/** True when none of an employee's tasks are still Pending (all Done or Skipped). */
function isEmployeeComplete(employeeTasks) {
  return employeeTasks.length > 0 && employeeTasks.every((t) => t.status !== 'Pending');
}

const flat = (v) => (Array.isArray(v) ? v[0] : v);
const p = $('Parse Callback').first().json;
const f = items[0].json;

const task = {
  id: f.id,
  assignee_telegram_id: f.Assignee_Telegram_ID,
  status: f.Status,
  employee_id: flat(f.Employee),
};
const r = resolveCallback({ task, fromTelegramId: p.from_id, action: p.action });

const answerText =
  r.outcome === 'unauthorized' ? 'This task is not assigned to you'
  : r.outcome === 'already-final' ? 'Already marked'
  : (r.status === 'Done' ? 'Marked done' : 'Marked not applicable');

return [{ json: {
  outcome: r.outcome,
  status: r.status || null,
  task_id: f.id,
  employee_id: task.employee_id,
  completed_by: p.from_username || String(p.from_id),
  telegram_message_id: f.Telegram_Message_ID,
  telegram_chat_id: f.Telegram_Chat_ID,
  callback_query_id: p.callback_query_id,
  answerText,
} }];
