// ============================================================================
// GENERATED by `npm run build:nodes` — DO NOT EDIT.
// Wrapper: workflows/code-nodes/expandTemplates.wrapper.js
// Core inlined verbatim from: scripts/dates.js, scripts/expandTemplates.js
// Paste this whole file into the n8n Code node.
// ============================================================================

// n8n Code node — "Expand templates"  (THIN WRAPPER — do not put logic here)
//
// The core (expandTemplates + its deps) is inlined by `npm run build:nodes` from
// scripts/ verbatim, replacing the __CORE__ marker. Edit logic in scripts/, never
// here. Paste the BUILT file (expandTemplates.built.js) into the n8n Code node.
//
// Upstream node names (rename the strings below if your workflow differs):
//   input items              -> valid employee records (IF "true" branch)
//   "Fetch Active Templates" -> Task_Templates rows
//   "Fetch Active Assignees" -> Assignees rows
//
// Output: one item PER TASK (json = Onboarding_Tasks fields). Unresolved assignees
// carry Unresolved_Assignee = true; the HR summary downstream is derived from those.

// ---- inlined from scripts/dates.js ----
// dates.js — due-date arithmetic for onboarding tasks.
//
// Pure and deterministic: operates only on the ISO string it is given, in UTC.
// No `Date.now()`, no local timezone, no external date library. This is on purpose —
// timezone only matters when comparing against "today" (notification / escalation
// logic), never in the offset arithmetic itself, so this module stays trivially
// testable outside n8n.
//
// dueDateFromOffset(startDate, offset):
//   Day_Offset is CALENDAR days (HR edits it and thinks calendar — "contract 3 days
//   before start"), added to the start date. If the result lands on a weekend it is
//   nudged to a working day, in the direction that keeps the deadline safe:
//     offset > 0  (after start)      -> shift FORWARD to Monday
//     offset < 0  (prep before start) -> shift BACKWARD to Friday, so a prep task
//                                        never slips onto or past the day it precedes
//     offset === 0 (the start day itself) -> returned as-is, never adjusted; per
//                                        SPEC F1 the start date does not move, only
//                                        task deadlines do
//   All I/O is ISO `YYYY-MM-DD`.

const ISO_RE = /^\d{4}-\d{2}-\d{2}$/;
const MS_PER_DAY = 86_400_000;

/** Parse a strict ISO date to a UTC timestamp, rejecting malformed or impossible dates. */
function parseISO(isoDate) {
  if (typeof isoDate !== 'string' || !ISO_RE.test(isoDate)) {
    throw new Error(`Invalid ISO date: ${JSON.stringify(isoDate)} (expected "YYYY-MM-DD")`);
  }
  const [y, m, d] = isoDate.split('-').map(Number);
  const ts = Date.UTC(y, m - 1, d);
  const back = new Date(ts);
  // Reject values JS would silently roll over, e.g. 2026-02-31 -> 2026-03-03.
  if (back.getUTCFullYear() !== y || back.getUTCMonth() !== m - 1 || back.getUTCDate() !== d) {
    throw new Error(`Invalid calendar date: ${isoDate}`);
  }
  return ts;
}

/** Format a UTC timestamp back to ISO `YYYY-MM-DD`. */
function toISO(ts) {
  const dt = new Date(ts);
  const y = dt.getUTCFullYear();
  const m = String(dt.getUTCMonth() + 1).padStart(2, '0');
  const d = String(dt.getUTCDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

function isWeekendTs(ts) {
  const day = new Date(ts).getUTCDay(); // 0 = Sun … 6 = Sat
  return day === 0 || day === 6;
}

/** True if the ISO date falls on Saturday or Sunday. */
function isWeekend(isoDate) {
  return isWeekendTs(parseISO(isoDate));
}

/**
 * Compute a task due date from the start date and a calendar-day offset, keeping the
 * result on a working day (see the sign rules in the file header).
 * @param {string} startDate - start date, ISO `YYYY-MM-DD`
 * @param {number} offset    - integer calendar-day offset; negative = before the start date
 * @returns {string} the resulting due date, ISO `YYYY-MM-DD`
 */
function dueDateFromOffset(startDate, offset) {
  if (!Number.isInteger(offset)) {
    throw new Error(`offset must be an integer, got: ${JSON.stringify(offset)}`);
  }
  let ts = parseISO(startDate) + offset * MS_PER_DAY;
  if (offset === 0) {
    return toISO(ts); // the start day itself — never weekend-adjusted
  }
  const step = offset > 0 ? MS_PER_DAY : -MS_PER_DAY; // forward for after-start, backward for prep
  while (isWeekendTs(ts)) {
    ts += step;
  }
  return toISO(ts);
}

// ---- inlined from scripts/expandTemplates.js ----
// expandTemplates.js — turn an employee + role templates into dated, assigned tasks.
//
// Pure and side-effect free: no network, no notifications. It returns
// `{ tasks, warnings }`; F2 (the n8n workflow) is responsible for de-duping against
// existing Task_Keys, writing the records, and messaging HR about the warnings.
//
// Shapes (plain values, as they arrive from Airtable rows in n8n):
//   employee  { id, full_name, work_email, role, start_date, manager_telegram_id }
//     - id: Airtable record id (the stable half of Task_Key)
//     - role: role name string, matched against template.role
//     - start_date: ISO YYYY-MM-DD
//   template  { id, title, description, role, applies_to_all, assignee_role, day_offset, active }
//   assignee  { name, assignee_role, telegram_id, active }
//
// Each returned task uses Airtable field names so the n8n Code node can write it
// almost verbatim (link fields Employee/Template are record ids; wrap as [id] on write).


const MANAGER_ROLE = 'Manager';

/**
 * A template is expanded for a role if it is active and either universal or role-matched.
 * Exported so validate.js applies the exact same selection when checking the Manager rule.
 */
function appliesToRole(template, role) {
  if (!template.active) return false;
  return template.applies_to_all === true || template.role === role;
}

/**
 * Resolve the Telegram id for a task's assignee role.
 * Manager resolves to the employee's own manager; every other role to the first active
 * assignee with that role. Returns { telegram_id, reason } — reason is set only on a miss.
 */
function resolveAssignee(assigneeRole, employee, assignees) {
  if (assigneeRole === MANAGER_ROLE) {
    const managerId = employee.manager_telegram_id;
    if (managerId) return { telegram_id: managerId };
    return { telegram_id: '', reason: 'Employee has no Manager_Telegram_ID' };
  }
  const match = assignees.find((a) => a.active && a.assignee_role === assigneeRole);
  if (match && match.telegram_id) return { telegram_id: match.telegram_id };
  return { telegram_id: '', reason: `No active assignee configured for role "${assigneeRole}"` };
}

/**
 * Expand a role's task templates into concrete onboarding tasks for one employee.
 * @returns {{ tasks: object[], warnings: {task_key:string, assignee_role:string, reason:string}[] }}
 */
function expandTemplates(employee, templates, assignees) {
  const tasks = [];
  const warnings = [];

  for (const template of templates) {
    if (!appliesToRole(template, employee.role)) continue;

    const taskKey = `${employee.id}::${template.id}`;
    const { telegram_id, reason } = resolveAssignee(template.assignee_role, employee, assignees);
    const unresolved = reason !== undefined;

    if (unresolved) {
      warnings.push({ task_key: taskKey, assignee_role: template.assignee_role, reason });
    }

    tasks.push({
      Task_Key: taskKey,
      Employee: employee.id,        // link (wrap as [id] when writing to Airtable)
      Template: template.id,        // link
      Title: template.title,        // snapshot at creation
      Description: template.description,
      Assignee_Role: template.assignee_role,
      Blocking: template.blocking === true, // snapshot, not read live from the template
      Category: template.category ?? null,  // snapshot too (used for dashboard grouping)
      Assignee_Telegram_ID: telegram_id,
      Due_Date: dueDateFromOffset(employee.start_date, template.day_offset),
      Status: 'Pending',
      Unresolved_Assignee: unresolved,
    });
  }

  return { tasks, warnings };
}

// --- n8n glue ---------------------------------------------------------------
const flat = (v) => (Array.isArray(v) ? v[0] : v);

const templates = $('Fetch Active Templates').all().map((i) => ({
  id: i.json.id,
  title: i.json.Title,
  description: i.json.Description,
  role: flat(i.json.Role_Name) ?? null,
  applies_to_all: i.json.Applies_To_All === true,
  assignee_role: i.json.Assignee_Role,
  day_offset: Number(i.json.Day_Offset),
  blocking: i.json.Blocking === true,
  category: i.json.Category ?? null,
  active: i.json.Active === true,
}));

const assignees = $('Fetch Active Assignees').all().map((i) => ({
  assignee_role: i.json.Assignee_Role,
  telegram_id: i.json.Telegram_ID != null ? String(i.json.Telegram_ID) : '',
  active: i.json.Active === true,
}));

const out = [];
for (const item of items) {
  const f = item.json;
  const employee = {
    id: f.id,
    role: flat(f.Role_Name),
    start_date: f.Start_Date,
    manager_telegram_id: f.Manager_Telegram_ID,
  };
  const { tasks } = expandTemplates(employee, templates, assignees);
  // Airtable link fields need arrays of record ids, not bare strings.
  for (const task of tasks) out.push({ json: { ...task, Employee: [task.Employee], Template: [task.Template] } });
}
return out;
