// ============================================================================
// GENERATED by `npm run build:nodes` — DO NOT EDIT.
// Wrapper: workflows/code-nodes/validate.wrapper.js
// Core inlined verbatim from: scripts/dates.js, scripts/expandTemplates.js, scripts/validate.js
// Paste this whole file into the n8n Code node.
// ============================================================================

// n8n Code node — "Validate intake"  (THIN WRAPPER — do not put logic here)
//
// The core (validate + its deps) is inlined by `npm run build:nodes`, which reads
// scripts/ verbatim and replaces the __CORE__ marker below. Edit logic in scripts/,
// never here. Paste the BUILT file (validate.built.js) into the n8n Code node.
//
// Upstream node names (rename the strings below if your workflow differs):
//   input items              -> New employee records
//   "Fetch Active Roles"     -> Roles rows
//   "Fetch Active Templates" -> Task_Templates rows
// Env: OFFICE_TIMEZONE (falls back to UTC).
//
// Output: one item per employee = original fields + { _valid, _errors }.

// ---- inlined from scripts/dates.js ----
// dates.js — due-date arithmetic for onboarding tasks.
//
// Pure and deterministic: operates only on the ISO string it is given, in UTC.
// No `Date.now()`, no local timezone, no external date library. This is on purpose —
// timezone only matters when comparing against "today" (notification / escalation
// logic), never in the offset arithmetic itself, so this module stays trivially
// testable outside n8n.
//
// dueDateFromOffset(startDate, offset):
//   Day_Offset is CALENDAR days (HR edits it and thinks calendar — "contract 3 days
//   before start"), added to the start date. If the result lands on a weekend it is
//   nudged to a working day, in the direction that keeps the deadline safe:
//     offset > 0  (after start)      -> shift FORWARD to Monday
//     offset < 0  (prep before start) -> shift BACKWARD to Friday, so a prep task
//                                        never slips onto or past the day it precedes
//     offset === 0 (the start day itself) -> returned as-is, never adjusted; per
//                                        SPEC F1 the start date does not move, only
//                                        task deadlines do
//   All I/O is ISO `YYYY-MM-DD`.

const ISO_RE = /^\d{4}-\d{2}-\d{2}$/;
const MS_PER_DAY = 86_400_000;

/** Parse a strict ISO date to a UTC timestamp, rejecting malformed or impossible dates. */
function parseISO(isoDate) {
  if (typeof isoDate !== 'string' || !ISO_RE.test(isoDate)) {
    throw new Error(`Invalid ISO date: ${JSON.stringify(isoDate)} (expected "YYYY-MM-DD")`);
  }
  const [y, m, d] = isoDate.split('-').map(Number);
  const ts = Date.UTC(y, m - 1, d);
  const back = new Date(ts);
  // Reject values JS would silently roll over, e.g. 2026-02-31 -> 2026-03-03.
  if (back.getUTCFullYear() !== y || back.getUTCMonth() !== m - 1 || back.getUTCDate() !== d) {
    throw new Error(`Invalid calendar date: ${isoDate}`);
  }
  return ts;
}

/** Format a UTC timestamp back to ISO `YYYY-MM-DD`. */
function toISO(ts) {
  const dt = new Date(ts);
  const y = dt.getUTCFullYear();
  const m = String(dt.getUTCMonth() + 1).padStart(2, '0');
  const d = String(dt.getUTCDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

function isWeekendTs(ts) {
  const day = new Date(ts).getUTCDay(); // 0 = Sun … 6 = Sat
  return day === 0 || day === 6;
}

/** True if the ISO date falls on Saturday or Sunday. */
function isWeekend(isoDate) {
  return isWeekendTs(parseISO(isoDate));
}

/**
 * Compute a task due date from the start date and a calendar-day offset, keeping the
 * result on a working day (see the sign rules in the file header).
 * @param {string} startDate - start date, ISO `YYYY-MM-DD`
 * @param {number} offset    - integer calendar-day offset; negative = before the start date
 * @returns {string} the resulting due date, ISO `YYYY-MM-DD`
 */
function dueDateFromOffset(startDate, offset) {
  if (!Number.isInteger(offset)) {
    throw new Error(`offset must be an integer, got: ${JSON.stringify(offset)}`);
  }
  let ts = parseISO(startDate) + offset * MS_PER_DAY;
  if (offset === 0) {
    return toISO(ts); // the start day itself — never weekend-adjusted
  }
  const step = offset > 0 ? MS_PER_DAY : -MS_PER_DAY; // forward for after-start, backward for prep
  while (isWeekendTs(ts)) {
    ts += step;
  }
  return toISO(ts);
}

// ---- inlined from scripts/expandTemplates.js ----
// expandTemplates.js — turn an employee + role templates into dated, assigned tasks.
//
// Pure and side-effect free: no network, no notifications. It returns
// `{ tasks, warnings }`; F2 (the n8n workflow) is responsible for de-duping against
// existing Task_Keys, writing the records, and messaging HR about the warnings.
//
// Shapes (plain values, as they arrive from Airtable rows in n8n):
//   employee  { id, full_name, work_email, role, start_date, manager_telegram_id }
//     - id: Airtable record id (the stable half of Task_Key)
//     - role: role name string, matched against template.role
//     - start_date: ISO YYYY-MM-DD
//   template  { id, title, description, role, applies_to_all, assignee_role, day_offset, active }
//   assignee  { name, assignee_role, telegram_id, active }
//
// Each returned task uses Airtable field names so the n8n Code node can write it
// almost verbatim (link fields Employee/Template are record ids; wrap as [id] on write).


const MANAGER_ROLE = 'Manager';

/**
 * A template is expanded for a role if it is active and either universal or role-matched.
 * Exported so validate.js applies the exact same selection when checking the Manager rule.
 */
function appliesToRole(template, role) {
  if (!template.active) return false;
  return template.applies_to_all === true || template.role === role;
}

/**
 * Resolve the Telegram id for a task's assignee role.
 * Manager resolves to the employee's own manager; every other role to the first active
 * assignee with that role. Returns { telegram_id, reason } — reason is set only on a miss.
 */
function resolveAssignee(assigneeRole, employee, assignees) {
  if (assigneeRole === MANAGER_ROLE) {
    const managerId = employee.manager_telegram_id;
    if (managerId) return { telegram_id: managerId };
    return { telegram_id: '', reason: 'Employee has no Manager_Telegram_ID' };
  }
  const match = assignees.find((a) => a.active && a.assignee_role === assigneeRole);
  if (match && match.telegram_id) return { telegram_id: match.telegram_id };
  return { telegram_id: '', reason: `No active assignee configured for role "${assigneeRole}"` };
}

/**
 * Expand a role's task templates into concrete onboarding tasks for one employee.
 * @returns {{ tasks: object[], warnings: {task_key:string, assignee_role:string, reason:string}[] }}
 */
function expandTemplates(employee, templates, assignees) {
  const tasks = [];
  const warnings = [];

  for (const template of templates) {
    if (!appliesToRole(template, employee.role)) continue;

    const taskKey = `${employee.id}::${template.id}`;
    const { telegram_id, reason } = resolveAssignee(template.assignee_role, employee, assignees);
    const unresolved = reason !== undefined;

    if (unresolved) {
      warnings.push({ task_key: taskKey, assignee_role: template.assignee_role, reason });
    }

    tasks.push({
      Task_Key: taskKey,
      Employee: employee.id,        // link (wrap as [id] when writing to Airtable)
      Template: template.id,        // link
      Title: template.title,        // snapshot at creation
      Description: template.description,
      Assignee_Role: template.assignee_role,
      Blocking: template.blocking === true, // snapshot, not read live from the template
      Category: template.category ?? null,  // snapshot too (used for dashboard grouping)
      Assignee_Telegram_ID: telegram_id,
      Due_Date: dueDateFromOffset(employee.start_date, template.day_offset),
      Status: 'Pending',
      Unresolved_Assignee: unresolved,
    });
  }

  return { tasks, warnings };
}

// ---- inlined from scripts/validate.js ----
// validate.js — new-hire intake validation (SPEC F1, step 1).
//
// Pure: collects ALL errors instead of throwing on the first, so HR sees every
// problem at once. Returns { valid, errors }, errors = [{ field, message }].
//
// `today` is injected (ISO YYYY-MM-DD) so the module stays testable and timezone-free.
// n8n must pass today's date in OFFICE_TIMEZONE; the default is UTC today as a fallback.


const REQUIRED_FIELDS = [
  ['full_name', 'Full name'],
  ['work_email', 'Work email'],
  ['role', 'Role'],
  ['department', 'Department'],
  ['start_date', 'Start date'],
];

function isBlank(value) {
  return value === undefined || value === null || String(value).trim() === '';
}

// Deliberately not an RFC regex — just enough to keep a broken address out of the
// dedupe key (F1) and IT's mailbox task: exactly one "@", both sides non-empty,
// and a dot inside the domain that is neither first nor last char.
function isValidEmail(value) {
  const parts = String(value).split('@');
  if (parts.length !== 2) return false;
  const [local, domain] = parts;
  if (local.trim() === '' || domain.trim() === '') return false;
  const dot = domain.indexOf('.');
  return dot > 0 && dot < domain.length - 1;
}

function utcTodayISO() {
  const now = new Date();
  const pad = (n) => String(n).padStart(2, '0');
  return `${now.getUTCFullYear()}-${pad(now.getUTCMonth() + 1)}-${pad(now.getUTCDate())}`;
}

/**
 * Validate a new-hire intake record.
 * @param {object} employee - { full_name, work_email, role, department, start_date, manager_telegram_id }
 * @param {object[]} roles - [{ role_name, active }]
 * @param {object[]} templates - [{ role, applies_to_all, assignee_role, active, ... }]
 * @param {string} [today] - ISO YYYY-MM-DD reference for "future"; defaults to UTC today
 * @returns {{ valid: boolean, errors: {field: string, message: string}[] }}
 */
function validate(employee, roles, templates, today = utcTodayISO()) {
  const errors = [];
  const emp = employee ?? {};

  // 1. Required fields present.
  for (const [field, label] of REQUIRED_FIELDS) {
    if (isBlank(emp[field])) {
      errors.push({ field, message: `${label} is required` });
    }
  }

  // 2. Email format (only when present — emptiness is already covered above).
  if (!isBlank(emp.work_email) && !isValidEmail(emp.work_email)) {
    errors.push({ field: 'work_email', message: `Work email is not a valid email address: ${emp.work_email}` });
  }

  // 3. Start date: valid ISO and strictly in the future (today is not the future).
  if (!isBlank(emp.start_date)) {
    let startTs;
    try {
      startTs = parseISO(emp.start_date);
    } catch {
      errors.push({ field: 'start_date', message: `Start date is not a valid date: ${emp.start_date}` });
    }
    if (startTs !== undefined && startTs <= parseISO(today)) {
      errors.push({ field: 'start_date', message: 'Start date must be in the future' });
    }
  }

  // 4. Role exists and is active.
  const role = roles.find((r) => r.role_name === emp.role);
  if (!isBlank(emp.role)) {
    if (!role) {
      errors.push({ field: 'role', message: `Role does not exist: ${emp.role}` });
    } else if (!role.active) {
      errors.push({ field: 'role', message: `Role is inactive: ${emp.role}` });
    }
  }

  // 5. Manager rule: manager_telegram_id is required only if the role has at least one
  //    active template assigned to the Manager (same selection as F2 expansion).
  const needsManager = templates.some(
    (t) => appliesToRole(t, emp.role) && t.assignee_role === 'Manager',
  );
  if (needsManager && isBlank(emp.manager_telegram_id)) {
    errors.push({
      field: 'manager_telegram_id',
      message: 'Manager Telegram ID is required because this role has manager-assigned tasks',
    });
  }

  return { valid: errors.length === 0, errors };
}

// --- n8n glue ---------------------------------------------------------------
// Airtable lookups/links come back as arrays; take the first scalar.
const flat = (v) => (Array.isArray(v) ? v[0] : v);

const tz = $env.OFFICE_TIMEZONE || 'UTC';
// en-CA gives YYYY-MM-DD; formatting in the office tz yields "today" as a plain date.
const today = new Date().toLocaleDateString('en-CA', { timeZone: tz });

const roles = $('Fetch Active Roles').all().map((i) => ({
  role_name: i.json.Role_Name,
  active: i.json.Active === true,
}));

const templates = $('Fetch Active Templates').all().map((i) => ({
  role: flat(i.json.Role_Name) ?? null,
  applies_to_all: i.json.Applies_To_All === true,
  assignee_role: i.json.Assignee_Role,
  active: i.json.Active === true,
}));

return items.map((item) => {
  const f = item.json;
  const employee = {
    id: f.id,
    full_name: f.Full_Name,
    work_email: f.Work_Email,
    role: flat(f.Role_Name),
    department: f.Department,
    start_date: f.Start_Date,
    manager_telegram_id: f.Manager_Telegram_ID,
  };
  const { valid, errors } = validate(employee, roles, templates, today);
  return { json: { ...f, _valid: valid, _errors: errors } };
});
